export const STARTUP_BANNER_DURATION_MS = 1800;

export const STARTUP_AVATAR_SPAWN_DURATION_MS = STARTUP_BANNER_DURATION_MS + 350;

export const STARTUP_MENU_FADE_DURATION_MS = 450;

export const STARTUP_MENU_FADE_DELAY_MS = Math.max(
	0,
	STARTUP_BANNER_DURATION_MS - STARTUP_MENU_FADE_DURATION_MS
);

export const STARTUP_AVATAR_SPAWN_DURATION_S = STARTUP_AVATAR_SPAWN_DURATION_MS / 1000;
