export const STARTUP_BANNER_DURATION_MS = 1800;

export const STARTUP_IDLE_CHROME_LEAD_MS = 250;

export const STARTUP_MENU_FADE_DURATION_MS = 450;

export const STARTUP_MENU_FADE_DELAY_MS = Math.max(
	0,
	STARTUP_BANNER_DURATION_MS - STARTUP_MENU_FADE_DURATION_MS
);

export const STARTUP_BANNER_DURATION_S = STARTUP_BANNER_DURATION_MS / 1000;
